### ISSUE TITLE
SameSite flag is not set when cookie is set in browser using javascript

### ISSUE THREAD

**Issue by pm-harshad-mane** [GoogleChromeLabs/samesite-examples#1]
Hello team,

I used the given JS snippet to set a cookie with SameSite=None;

```java
document.cookie = 'cross-site-cookie=bar; SameSite=None; Secure';
```

But I do not see "None" value in SameSite column in Chrome Dev Toolbar -> Application -> Cookies. Is it the desired behavior? 
I can see "None" value in SameSite column in Chrome Dev Toolbar -> Application -> Cookies when I try to set a cookie from http-header in a response from a server.

**Comment by pm-harshad-mane** [comment]
Hello @rowan-m ,
Can you help me understand?

**Comment by pm-harshad-mane** [comment]
Moreover,
Following two snippets work fine.
```java
document.cookie = 'cross-site-cookie=bar; SameSite=Lax';
```

```java
document.cookie = 'cross-site-cookie=bar; SameSite=Strict';
```

**Comment by pm-harshad-mane** [comment]
I tried this as well but it does not work,

```java
document.cookie = 'cross-site-cookie=bar; SameSite=None';
```

**Comment by pm-harshad-mane** [comment]
Hello @rowan-m ,
Can you help?

**Comment by rowan-m** [comment]
@pm-harshad-mane I think the issue here may be that you are using an earlier version of Chrome. You need at least Chrome 76 for the `None` attribute to be registered. Earlier versions of Chrome will set the cookie, but  ignore the `None` value as they don't understand it. This is the intended behaviour as `SameSite=None` is the equivalent of the default at the moment. I've [added a note to the README](https://github.com/GoogleChromeLabs/samesite-examples/commit/c466c505e59260a956e65e246a0345ec3b15c084#diff-04c6e90faac2675aa89e2176d2eec7d8R73) to hopefully make this clearer.

I would also ensure that you are setting **both** `SameSite=None` and `Secure` together as this will be the default behaviour later.

Let me know if that makes sense!

**Comment by pm-harshad-mane** [comment]
Thanks for the feedback @rowan-m , 
I think I am using Chrome 76, let me check again.
Makes sense to add secure flag as well, do you know from which version secure flag will become mandatory?

**Comment by rowan-m** [comment]
I've linked this from the README, both features are planned for Chrome 80.

- https://www.chromestatus.com/feature/5088147346030592
- https://chromestatus.com/feature/5633521622188032

**Comment by rowan-m** [comment]
Let me know if you're still having issues!

**Comment by oods** [comment]
Where would i add the SameSite attribute into my html code? Can you maybe help?

**Comment by oods** [comment]
The reason I need to add the SameSite attribute is because i have a payment gateway on my site, and it is not allowing any users to make payment, i even tried this myself

**Comment by ganeshn309** [comment]
> The reason I need to add the SameSite attribute is because i have a payment gateway on my site, and it is not allowing any users to make payment, i even tried this myself

Hello, I am facing exactly the same issue. Did you find the solution for this. Can you please share me the solution. Thank you

**Comment by viniciusrad** [comment]
i'm stuck on that too. I have an iframe in a legacy application that stopped working in chrome.

**Comment by rowan-m** [comment]
Hey all, this is an old, closed issue. For problems that are specific to your particular site, it's best to raise a question under the SameSite tag on StackOverflow. Please include as much information as you can about your environment and the cookies you are using.

https://stackoverflow.com/questions/tagged/samesite
