### ISSUE TITLE
[Question] Not treat cookies as SameSite=Lax by default in "document.cookie" on Browser ?

### ISSUE THREAD

**Issue by y-tomimoto** [GoogleChromeLabs/samesite-examples#42]
Hi @rowan-m

I wrote this script in _Chrome console (84.0.4147.105)_,

```js
document.cookie="test=123"
```

and then checked Chrome Developper Tools, 

but there are **no Samesite attribute with "Lax".**

![image](https://user-images.githubusercontent.com/31181316/96073890-5d8f4400-0ee2-11eb-947a-a556a1dc39f9.png)

[Question]
Not treat cookies as SameSite=Lax by default in "document.cookie" on Browser ?

According to the document, I had a different result in mind.
> Treat cookies as SameSite=Lax by default if no SameSite attribute is specified. 
>> https://www.chromestatus.com/feature/5088147346030592

If so, are there any official announcement about this case ?

**Comment by rowan-m** [comment]
DevTools is showing the value that was _explicitly set_ with the cookie. If you do not provide an attribute, the cookie will be treated in the same way _as if_ it specified `Lax`. For example, compare:

```js
document.cookie = 'test1=123';
document.cookie = 'test2=123; SameSite=Lax';
```

![Screenshot from 2020-10-15 12-54-18](https://user-images.githubusercontent.com/108052/96119894-90870700-0ee5-11eb-88c7-93c07c8c82ba.png)

Both cookies will be treated in the same way because `Lax` is the new default behaviour, but it will only show you the values actually provided when the cookie was set.

**Comment by y-tomimoto** [comment]
Thank you for your prompt reply! 

Is it okay if I add a note about this to this repo ? ( such as https://github.com/GoogleChromeLabs/samesite-examples/blob/master/javascript.md )
